# Generated by Django 3.2.9 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qadocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadocument',
            name='guild_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qadocument',
            name='model',
            field=models.TextField(default='text-similarity-ada-001'),
        ),
    ]
