# Generated by Django 3.2.9 on 2022-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220308_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadocument',
            name='embedding_vector',
            field=models.BinaryField(),
        ),
    ]
