# Generated by Django 3.2.9 on 2022-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_qadocument_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
