# Generated by Django 3.2.9 on 2022-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220314_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('prompt', models.TextField()),
                ('user_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
