# Generated by Django 3.2.9 on 2022-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_unansweredquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
