# Generated by Django 3.2.9 on 2022-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_qadocument_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_avatar_hash',
            field=models.TextField(blank=True, null=True),
        )
    ]
