# Generated by Django 3.2.9 on 2022-03-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220324_1237'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
