# Generated by Django 3.2.9 on 2022-04-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadocument',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_qa_questions', to=settings.AUTH_USER_MODEL, to_field='discord_user_id'),
        ),
    ]
