# Generated by Django 3.2.9 on 2022-04-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220407_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('UNANSWERED_QUESTION', 'UNANSWERED_QUESTION'), ('ANSWERED_QUESTION', 'ANSWERED_QUESTION')])),
                ('user_prompt', models.TextField()),
                ('bot_response', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='api.community', to_field='guild_id')),
                ('related_qa_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_event_logs', to='api.qadocument')),
                ('triggered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_event_logs', to=settings.AUTH_USER_MODEL, to_field='discord_user_id')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
