# Generated by Django 3.2.9 on 2022-04-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220407_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.community')),
                ('qa_documents', models.ManyToManyField(related_name='tags', to='api.QaDocument')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
