# Generated by Django 3.2.9 on 2022-04-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_eventlog'),
        ('api', '0013_tag'),
    ]

    operations = [
    ]
