# Generated by Django 3.2.9 on 2022-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220419_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='minimum_threshold',
            field=models.FloatField(default=0.9),
        ),
    ]
