# Generated by Django 3.2.9 on 2022-04-27 13:54

import api.models.community
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220427_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='minimum_threshold',
            field=api.models.community.FloatRangeField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
