# Generated by Django 3.2.9 on 2022-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_community_minimum_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadocument',
            name='answer_jump_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qadocument',
            name='question_jump_url',
            field=models.TextField(null=True),
        ),
    ]
