# Generated by Django 3.2.9 on 2022-05-04 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220429_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('command', models.CharField(max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_flows', to='api.community')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('step_text', models.TextField()),
                ('help_text', models.TextField(null=True)),
                ('guided_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_flow_steps', to='api.guidedflow')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedFlowStepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('button_label', models.TextField()),
                ('flow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_actions', to='api.guidedflowstep')),
                ('triggered_next_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by_action', to='api.guidedflowstep')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guidedflow',
            name='initial_step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_step', to='api.guidedflowstep'),
        ),
        migrations.AddField(
            model_name='guidedflow',
            name='moderators_to_contact',
            field=models.ManyToManyField(related_name='moderated_guided_flows', to=settings.AUTH_USER_MODEL),
        ),
    ]
