# Generated by Django 3.2.9 on 2022-05-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220504_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstepaction',
            name='triggered_next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by_actions', to='api.guidedflowstep'),
        ),
    ]
