# Generated by Django 3.2.9 on 2022-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_guidedflowstep_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflowstepaction',
            name='button_style',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Success'), (4, 'Danger')], default=3, max_length=50),
        ),
    ]
