# Generated by Django 3.2.9 on 2022-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_guidedflowstepaction_button_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidedflow',
            options={},
        ),
        migrations.AddField(
            model_name='guidedflow',
            name='flow_label',
            field=models.CharField(default='onboarding', max_length=50),
        ),
        migrations.AlterField(
            model_name='guidedflow',
            name='command',
            field=models.CharField(default='onboard', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='guidedflow',
            unique_together={('community', 'command'), ('community', 'flow_label')},
        ),
    ]
