# Generated by Django 3.2.9 on 2022-05-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_guidedflow_channel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guidedflow',
            unique_together={('community', 'command'), ('community', 'channel_name'), ('community', 'flow_label')},
        ),
    ]
