# Generated by Django 3.2.9 on 2022-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_guidedflow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflow',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
