# Generated by Django 3.2.9 on 2022-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220516_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflowstep',
            name='granted_role_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
