# Generated by Django 3.2.9 on 2022-05-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_guidedflowstep_granted_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflow',
            name='initial_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_step', to='api.guidedflowstep'),
        ),
    ]
