# Generated by Django 3.2.9 on 2022-05-18 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_guidedflow_initial_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflowstep',
            name='granted_role_needs_approval_by',
            field=models.ManyToManyField(related_name='managed_guided_flow_steps_role_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
