# Generated by Django 3.2.9 on 2022-05-18 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_guidedflowstep_granted_role_needs_approval_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstep',
            name='granted_role_needs_approval_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_guided_flow_steps_role_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
