# Generated by Django 3.2.9 on 2022-05-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_guidedflowstep_granted_role_needs_approval_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedFlowStepAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guidedflowstep')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
