# Generated by Django 3.2.9 on 2022-05-23 13:35

import api.models.guided_flow_step_attached_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_guidedflowstepattachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstepattachedfile',
            name='file',
            field=models.FileField(upload_to=api.models.guided_flow_step_attached_file.get_file_path),
        ),
    ]
