# Generated by Django 3.2.9 on 2022-05-26 20:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_guidedflowstepattachedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflow',
            name='abstractbotevent_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guidedflowstep',
            name='abstractboteventhandler_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guidedflowstepaction',
            name='abstractbotevent_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='guidedflow',
            old_name='command',
            new_name='slash_command_name'
        ),
        migrations.AlterUniqueTogether(
            name='guidedflow',
            unique_together={('community', 'slash_command_name'), ('community', 'channel_name'), ('community', 'flow_label')},
        )
    ]
