# Generated by Django 3.2.9 on 2022-05-26 21:29

from django.db import migrations, models
import django.db.models.deletion

def populate_pointers(apps, schema_editor):
    AbstractBotEvent = apps.get_model("api", "AbstractBotEvent")
    GuidedFlow = apps.get_model("api", "GuidedFlow")
    GuidedFlowStepAction = apps.get_model("api", "GuidedFlowStepAction")

    AbstractBotEventHandler = apps.get_model("api", "AbstractBotEventHandler")
    GuidedFlowStep = apps.get_model("api", "GuidedFlowStep")

    for model, base_model, field_name, id_field in [(GuidedFlow, AbstractBotEvent, "abstractbotevent_ptr", "event_id"),
                                                    (GuidedFlowStepAction, AbstractBotEvent, "abstractbotevent_ptr", "event_id"),
                                                    (GuidedFlowStep, AbstractBotEventHandler, "abstractboteventhandler_ptr", "event_handler_id")]:
        for obj in model.objects.all():
            base = base_model.objects.create()
            setattr(obj, field_name, getattr(base, id_field))
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220526_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBotEventHandler',
            fields=[
                ('event_handler_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['event_handler_id'],
            },
        ),
        migrations.CreateModel(
            name='DeleteCurrentThreadAction',
            fields=[
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractboteventhandler')),
            ],
            bases=('api.abstractboteventhandler',),
        ),
        migrations.CreateModel(
            name='AbstractBotEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('triggered_handlers', models.ManyToManyField(related_name='triggered_by', to='api.AbstractBotEventHandler')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
        migrations.RunPython(populate_pointers),
        migrations.AlterField(
            model_name='guidedflow',
            name='abstractbotevent_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidedflowstep',
            name='abstractboteventhandler_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractboteventhandler'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidedflowstepaction',
            name='abstractbotevent_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent'),
            preserve_default=False,
        ),
    ]
