# # Generated by Django 3.2.9 on 2022-05-26 20:26
#
from django.db import migrations

def migrate_button_triggered_actions(apps, schema_editor):
    GuidedFlowStepButton = apps.get_model("api", "GuidedFlowStepButton")
    AbstractBotEventHandler = apps.get_model("api", "AbstractBotEventHandler")
    AbstractBotEvent = apps.get_model("api", "AbstractBotEvent")
    for button in GuidedFlowStepButton.objects.all():
        value = button.triggered_next_step
        if value is not None:
            value = AbstractBotEventHandler.objects.get(pk=value.abstractboteventhandler_ptr_id)
            AbstractBotEvent.objects.get(pk=button.abstractbotevent_ptr_id).triggered_handlers.add(value)

def create_single_delete_thread(apps, schema_editor):
    DeleteCurrentThread = apps.get_model("api", "DeleteCurrentThread")
    DeleteCurrentThread.objects.create()

class Migration(migrations.Migration):
    pass
    dependencies = [
        ('api', '0035_20220526_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuidedFlowStepAction',
            new_name='GuidedFlowStepButton',
        ),
        migrations.RunPython(migrate_button_triggered_actions),
        migrations.RenameModel(
            old_name='DeleteCurrentThreadAction',
            new_name='DeleteCurrentThread',
        ),
        migrations.RunPython(create_single_delete_thread)
    ]
