# Generated by Django 3.2.9 on 2022-05-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_guidedflowstepaction_guidedflowstepbutton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedflowstepbutton',
            name='triggered_next_step',
        ),
    ]
