# Generated by Django 3.2.9 on 2022-05-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_guidedflowstepbutton_triggered_next_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstepbutton',
            name='flow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_buttons', to='api.guidedflowstep'),
        ),
    ]
