# # Generated by Django 3.2.9 on 2022-05-26 20:26
#
from django.db import migrations

def migrate_flow_initial_steps(apps, schema_editor):
    GuidedFlow = apps.get_model("api", "GuidedFlow")
    AbstractBotEventHandler = apps.get_model("api", "AbstractBotEventHandler")
    AbstractBotEvent = apps.get_model("api", "AbstractBotEvent")
    for flow in GuidedFlow.objects.all():
        value = flow.initial_step
        if value is None:
            continue
        value = AbstractBotEventHandler.objects.get(pk=value.abstractboteventhandler_ptr_id)
        AbstractBotEvent.objects.get(pk=flow.abstractbotevent_ptr_id).triggered_handlers.add(value)

class Migration(migrations.Migration):
    pass
    dependencies = [
        ('api', '0038_alter_guidedflowstepbutton_flow_step'),
    ]

    operations = [
        migrations.RunPython(migrate_flow_initial_steps)
    ]
