# Generated by Django 3.2.9 on 2022-05-30 13:58

from django.db import migrations, models
import django.db.models.deletion

def create_single_archive_thread(apps, schema_editor):
    ArchiveCurrentThread = apps.get_model("api", "ArchiveCurrentThread")
    ArchiveCurrentThread.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_migrate_initial_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCurrentThread',
            fields=[
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractboteventhandler')),
            ],
            bases=('api.abstractboteventhandler',),
        ),
        migrations.RunPython(create_single_archive_thread),
        migrations.AlterField(
            model_name='guidedflowstepattachedfile',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='api.guidedflowstep'),
        ),
    ]
