# Generated by Django 3.2.9 on 2022-05-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220530_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedflow',
            name='initial_step',
        ),
    ]
