# Generated by Django 3.2.9 on 2022-05-31 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_abstractbotevent_triggered_handlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteUsersToCurrentThread',
            fields=[
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractboteventhandler')),
                ('users_to_invite', models.ManyToManyField(related_name='users_to_be', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.abstractboteventhandler',),
        ),
    ]
