# Generated by Django 3.2.9 on 2022-05-31 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_inviteuserstocurrentthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflow',
            name='moderators_to_contact',
            field=models.ManyToManyField(blank=True, related_name='moderated_guided_flows', to=settings.AUTH_USER_MODEL),
        ),
    ]
