# Generated by Django 3.2.9 on 2022-05-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220531_1155'),
        ('api', '0044_alter_guidedflow_moderators_to_contact'),
    ]

    operations = [
    ]
