# Generated by Django 3.2.9 on 2022-06-02 17:34

from django.db import migrations, models
import django.db.models.deletion

def create_single_show_ticket_modal(apps, schema_editor):
    DeleteCurrentThread = apps.get_model("api", "ShowTicketModal")
    DeleteCurrentThread.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_showticketmodal'),
    ]

    operations = [
        migrations.RunPython(create_single_show_ticket_modal)
    ]
