# Generated by Django 3.2.9 on 2022-06-03 14:11

from django.db import migrations, models
import django.db.models.deletion

def create_single_trigger_callback(apps, schema_editor):
    TriggerCallback = apps.get_model("api", "TriggerCallback")
    TriggerCallback.objects.create()

def populate_pointers(apps, schema_editor):
    AbstractBotEventHandler = apps.get_model("api", "AbstractBotEventHandler")
    GuidedFlow = apps.get_model("api", "GuidedFlow")

    for model, base_model, field_name, id_field in [(GuidedFlow, AbstractBotEventHandler, "abstractboteventhandler_ptr", "event_handler_id")]:
        for obj in model.objects.all():
            base = base_model.objects.create()
            setattr(obj, field_name, getattr(base, id_field))
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_create_showticketmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerCallback',
            fields=[
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractboteventhandler')),
            ],
            bases=('api.abstractboteventhandler',),
        ),
        migrations.AddField(
            model_name='guidedflow',
            name='abstractboteventhandler_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(create_single_trigger_callback),
        migrations.RunPython(populate_pointers)
    ]
