# Generated by Django 3.2.9 on 2022-06-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_abstractbotevent_handler_callbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflow',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guided_flows', to='api.community'),
        ),
    ]
