# Generated by Django 3.2.9 on 2022-06-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_inviteuserswithroletocurrentthread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedflow',
            name='channel_entrypoint_id',
        ),
    ]
