# Generated by Django 3.2.9 on 2022-06-17 08:56

import api.models.permanent_embed_attached_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_guidedflow_channel_entrypoint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentEmbedAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=api.models.permanent_embed_attached_file.get_file_path)),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='api.permanentembed')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
