# Generated by Django 3.2.9 on 2022-06-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_permanentembedattachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='api.community', to_field='guild_id'),
        ),
    ]
