# Generated by Django 3.2.9 on 2022-06-23 11:54

from django.db import migrations, models


def populate_pointers(apps, schema_editor):
    AbstractBotEvent = apps.get_model("api", "AbstractBotEvent")
    ShowTicketModal = apps.get_model("api", "ShowTicketModal")

    for model, base_model, field_name, id_field in [(ShowTicketModal, AbstractBotEvent, "abstractbotevent_ptr", "event_id")]:
        for obj in model.objects.all():
            base = base_model.objects.create()
            setattr(obj, field_name, getattr(base, id_field))
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_eventlog_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticketmodal',
            name='abstractbotevent_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_pointers)
    ]
