# Generated by Django 3.2.9 on 2022-06-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_showticketmodal_abstractbotevent_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showticketmodal',
            name='abstractbotevent_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent'),
            preserve_default=False,
        ),
    ]
