# Generated by Django 3.2.9 on 2022-06-29 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_migrate_showmodal_singleton_to_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCustomModal',
            fields=[
                ('abstractbotevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent')),
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractboteventhandler')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('api.abstractboteventhandler', 'api.abstractbotevent', models.Model),
        ),
        migrations.CreateModel(
            name='CustomModalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(choices=[('TEXT_INPUT', 'TEXT_INPUT')])),
                ('label', models.TextField()),
                ('placeholder', models.TextField(default='')),
                ('style', models.TextField(choices=[('SHORT', 'SHORT'), ('LONG', 'LONG')])),
                ('min_length', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3999), django.core.validators.MinValueValidator(0)])),
                ('max_length', models.IntegerField(default=3999, validators=[django.core.validators.MaxValueValidator(3999), django.core.validators.MinValueValidator(1)])),
                ('required', models.BooleanField(default=True)),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.showcustommodal')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
