# Generated by Django 3.2.9 on 2022-06-30 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220629_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSelectMenu',
            fields=[
                ('abstractbotevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent')),
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractboteventhandler')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('message_text', models.TextField(default='')),
                ('placeholder', models.TextField(default='')),
                ('min_values', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
                ('max_values', models.IntegerField(default=3999, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('api.abstractboteventhandler', 'api.abstractbotevent', models.Model),
        ),
        migrations.CreateModel(
            name='SelectMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('label', models.TextField()),
                ('description', models.TextField(default='')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.showselectmenu')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
