# Generated by Django 3.2.9 on 2022-06-30 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_selectmenuoption_showselectmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showselectmenu',
            name='max_values',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='showselectmenu',
            name='min_values',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(1)]),
        ),
    ]
