# Generated by Django 3.2.9 on 2022-07-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_showselectmenu_min_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflowstep',
            name='file_upload_triggered_handlers',
            field=models.ManyToManyField(blank=True, related_name='triggered_by_file_upload', to='api.AbstractBotEventHandler'),
        ),
        migrations.AddField(
            model_name='guidedflowstep',
            name='supported_files_formats_csv',
            field=models.TextField(blank=True, help_text="Comma separated file formats, e.g. 'png,jpg,gif'. Leave blank to support all file formats", null=True),
        ),
    ]
