# Generated by Django 3.2.9 on 2022-07-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20220704_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstep',
            name='file_upload_triggered_handlers',
            field=models.ManyToManyField(blank=True, help_text='Note: 1) currently does not work inside subflows; \n2) currently can trigger only flow steps', related_name='triggered_by_file_upload', to='api.AbstractBotEventHandler'),
        ),
        migrations.CreateModel(
            name='DiscordMessageMapping',
            fields=[
                ('discord_message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('callback_ids_sets', models.JSONField()),
                ('flow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mappings', to='api.guidedflowstep')),
            ],
        ),
    ]
