# Generated by Django 3.2.9 on 2022-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20220706_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflow',
            name='auto_archive_duration',
            field=models.IntegerField(choices=[(60, 60), (1440, 1440), (4320, 4320), (10080, 10080)], default=1440),
        ),
        migrations.AlterField(
            model_name='guidedflowstep',
            name='file_upload_triggered_handlers',
            field=models.ManyToManyField(blank=True, related_name='triggered_by_file_upload', to='api.AbstractBotEventHandler'),
        ),
    ]
