# Generated by Django 3.2.9 on 2022-07-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_guidedflowstepuseruploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.JSONField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.abstractbotevent')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
