# Generated by Django 3.2.9 on 2022-07-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_guidedflowstepuseruploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscordChannel',
            new_name='BotEnabledDiscordChannel',
        ),
    ]
