# Generated by Django 3.2.9 on 2022-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_eventrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='channel_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='discord_user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='guild_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='source',
            field=models.CharField(choices=[('modal', 'Modal'), ('select', 'Select Menu')], max_length=25, null=True),
        ),
    ]
