# Generated by Django 3.2.9 on 2022-07-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220714_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('channel_name', models.TextField(default='')),
                ('channel_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_discord_channels', to='api.community')),
            ],
            options={
                'db_table': 'api_alldiscordchanels',
            },
        ),
    ]
