# Generated by Django 3.2.9 on 2022-07-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_discordchannel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botenableddiscordchannel',
            table='api_botenableddiscordchannel',
        ),
    ]
