# Generated by Django 3.2.9 on 2022-07-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220713_1338'),
        ('api', '0072_alter_botenableddiscordchannel_table'),
    ]

    operations = [
    ]
