# Generated by Django 3.2.9 on 2022-07-14 15:49

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_20220714_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='botenableddiscordchannel',
            name='channel_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_enabled_discord_channel', to='api.discordchannel'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='source',
            field=models.CharField(choices=[('modal', 'Modal'), ('select-menu', 'Select Menu')], max_length=25, null=True),
        ),
    ]
