# Generated by Django 3.2.9 on 2022-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20220714_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstep',
            name='help_text',
            field=models.TextField(blank=True, max_length=1990, null=True),
        ),
        migrations.AlterField(
            model_name='guidedflowstep',
            name='step_text',
            field=models.TextField(max_length=1990),
        ),
    ]
