# # Generated by Django 3.2.9 on 2022-05-26 20:26
#
from django.db import migrations

def discord_channel_migrate_refs(apps, schema_editor):
    DiscordChannel = apps.get_model("api", "DiscordChannel")
    BotEnabledDiscordChannel = apps.get_model("api", "BotEnabledDiscordChannel")
    for channel in BotEnabledDiscordChannel.objects.all():
        channel_id = channel.channel_id
        ch = DiscordChannel.objects.filter(channel_id=channel_id,
                                           channel_community=channel.community).first()
        if ch is None:
            print('invalid discord channel config')
            print(f'channel - {channel_id}')
            print(channel)
            print(f'guild id - {channel.community.guild_id}')
            print("Deleting it")

            channel.delete()
        else:
            channel.channel_ref = ch
            channel.save()

class Migration(migrations.Migration):
    pass
    dependencies = [
        ('api', '0074_auto_20220714_1549'),
    ]

    operations = [
        migrations.RunPython(discord_channel_migrate_refs)
    ]
