# Generated by Django 3.2.9 on 2022-07-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20220714_1707'),
        ('api', '0075_migrate_channnel_refs'),
    ]

    operations = [
    ]
