# Generated by Django 3.2.9 on 2022-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_merge_20220715_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botenableddiscordchannel',
            name='channel_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
