# Generated by Django 3.2.9 on 2022-07-18 14:21

from django.db import migrations, models

def populate_pointers(apps, schema_editor):
    AbstractBotEvent = apps.get_model("api", "AbstractBotEvent")
    SelectMenuOption = apps.get_model("api", "SelectMenuOption")

    for model, base_model, field_name, id_field in [(SelectMenuOption, AbstractBotEvent, "abstractbotevent_ptr", "event_id")]:
        for obj in model.objects.all():
            base = base_model.objects.create()
            setattr(obj, field_name, getattr(base, id_field))
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_botenableddiscordchannel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectmenuoption',
            name='abstractbotevent_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_pointers)
    ]
