# Generated by Django 3.2.9 on 2022-07-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_selectmenuoption_abstractbotevent_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentembed',
            name='channel_entrypoint_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_embeds', to='api.discordchannel'),
        ),
    ]
