# # Generated by Django 3.2.9 on 2022-05-26 20:26
#
from django.db import migrations

def perm_embed_migrate_refs(apps, schema_editor):
    DiscordChannel = apps.get_model("api", "DiscordChannel")
    PermanentEmbed = apps.get_model("api", "PermanentEmbed")
    for embed in PermanentEmbed.objects.all():
        channel_entrypoint_id = embed.channel_entrypoint_id
        ch = DiscordChannel.objects.filter(channel_id=channel_entrypoint_id
                                           #channel_community=embed.community
        ).first()
        if ch is None:
            print('invalid discord channel config')
            print(f'channel - {channel_entrypoint_id}')
            print(embed)
            print(f'guild id - {embed.community.guild_id if embed.community is not None else "none"}')
            print("Ignoring it")

            # channel.delete()
        else:
            embed.channel_entrypoint_ref = ch
            embed.save()

class Migration(migrations.Migration):
    pass
    dependencies = [
        ('api', '0080_permanentembed_channel_entrypoint_ref'),
    ]

    operations = [
        migrations.RunPython(perm_embed_migrate_refs)
    ]
