# Generated by Django 3.2.9 on 2022-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_migrate_embed_channnel_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectmenuoption',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
