# Generated by Django 3.2.9 on 2022-07-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_qadocumentcompletionbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCaptcha',
            fields=[
                ('abstractbotevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractbotevent')),
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.abstractboteventhandler')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=('api.abstractboteventhandler', 'api.abstractbotevent'),
        ),
    ]
