# Generated by Django 3.2.9 on 2022-07-31 03:37

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_showcaptcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('equation_string', models.CharField(max_length=30)),
                ('equation_result', models.CharField(max_length=30)),
                ('image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='bn-bot-capcha-resources'), upload_to='test-image')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
