# Generated by Django 3.2.9 on 2022-08-09 21:35

import django.core.validators
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_guidedflow_is_ephemeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaFailuresCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('discord_user_id', models.BigIntegerField(unique=True)),
                ('failure_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3999), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='captcharequest',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='bn-bot-capcha-resources'), upload_to=''),
        ),
    ]
