# Generated by Django 3.2.9 on 2022-08-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20220809_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadocument',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revision Date'),
        ),
    ]
