# Generated by Django 3.2.9 on 2022-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_community_admin_role_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='discord_user_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
