# Generated by Django 3.2.9 on 2022-08-29 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_eventrecord_discord_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantRole',
            fields=[
                ('abstractboteventhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractboteventhandler')),
                ('granted_role_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('granted_role_needs_approval_by', models.ManyToManyField(blank=True, null=True, related_name='managed_granted_roles', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.abstractboteventhandler',),
        ),
    ]
