# Generated by Django 3.2.9 on 2022-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_grantrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantrole',
            name='label',
            field=models.TextField(blank=True, help_text='Not used by bot. Used only as a label in admin panel', null=True),
        ),
    ]
