# Generated by Django 3.2.9 on 2022-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20220830_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflow',
            name='google_spreadsheet_id',
            field=models.CharField(blank=True, help_text='Spreadsheet ID where to export menu/modal submissions.\nMake sure bot has edit access to this spreadsheet. \nSpreadsheet ID can be found in spreadsheet URL - https://docs.google.com/spreadsheets/d/{ID}/edit#gid=0.\nSubmissions are exported daily', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showcustommodal',
            name='google_spreadsheet_id',
            field=models.CharField(blank=True, help_text='Spreadsheet ID where to export modal submissions.\nMake sure bot has edit access to this spreadsheet. \nSpreadsheet ID can be found in spreadsheet URL - https://docs.google.com/spreadsheets/d/{ID}/edit#gid=0.\nSubmissions are exported daily', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showselectmenu',
            name='google_spreadsheet_id',
            field=models.CharField(blank=True, help_text='Spreadsheet ID where to export menu submissions.\nMake sure bot has edit access to this spreadsheet. \nSpreadsheet ID can be found in spreadsheet URL - https://docs.google.com/spreadsheets/d/{ID}/edit#gid=0.\nSubmissions are exported daily', max_length=100, null=True),
        ),
    ]
