# Generated by Django 3.2.9 on 2022-09-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_showcaptcha_verify_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='kick_users_ignore_datetime_before_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
