# Generated by Django 3.2.9 on 2022-09-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20220916_1851'),
        ('api', '0109_auto_20220920_1344'),
    ]

    operations = [
    ]
