# Generated by Django 3.2.9 on 2022-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_merge_0107_auto_20220916_1851_0109_auto_20220920_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedflowstep',
            name='guided_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guided_flow_steps', to='api.guidedflow'),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='question_1_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='question_2_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='question_3_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='question_4_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='question_5_required',
            field=models.BooleanField(default=False),
        ),
    ]
