# Generated by Django 3.2.9 on 2022-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20220921_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedflowstepbutton',
            name='button_row',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='permanentembedbutton',
            name='button_row',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
