# Generated by Django 3.2.9 on 2022-10-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20220926_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='channel_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='guild_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onboardingflowcreationobject',
            name='role_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
