# Generated by Django 3.2.9 on 2022-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_onboardingflowcreationobject_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingflowcreationobject',
            name='permanent_embed_channel_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onboardingflowcreationobject',
            name='permanent_embed_message_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
