# Generated by Django 3.2.9 on 2022-10-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20221018_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaDocumentAlternativePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_prompt', models.TextField()),
                ('qa_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_prompts', to='api.qadocument')),
            ],
        ),
    ]
