# Generated by Django 3.2.9 on 2022-10-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_qadocumentalternativeprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadocumentalternativeprompt',
            name='embedding_vector',
            field=models.BinaryField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qadocumentalternativeprompt',
            name='model',
            field=models.TextField(default='text-similarity-ada-001'),
        ),
    ]
