# Generated by Django 3.2.9 on 2022-10-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20221019_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadocument',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_qa_documents', to=settings.AUTH_USER_MODEL, to_field='discord_user_id'),
        ),
        migrations.AlterField(
            model_name='qadocument',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_qa_documents', to=settings.AUTH_USER_MODEL, to_field='discord_user_id'),
        ),
    ]
