# Generated by Django 3.2.9 on 2022-10-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20221019_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadocument',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_qa_questions', to=settings.AUTH_USER_MODEL, to_field='discord_user_id'),
        ),
    ]
