# Generated by Django 3.2.9 on 2022-10-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_qadocument_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodalfield',
            name='label',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='custommodalfield',
            name='placeholder',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='selectmenuoption',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='selectmenuoption',
            name='label',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='showselectmenu',
            name='placeholder',
            field=models.TextField(default='', max_length=150),
        ),
    ]
