# Generated by Django 3.2.9 on 2022-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20221024_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='kick_users_who_joined_but_did_not_verify_after_hours',
            field=models.IntegerField(default=0, help_text='If both days and hours are provided, they are summed up'),
        ),
    ]
