# # Generated by Django 3.2.9 on 2022-05-26 20:26
#
from django.db import migrations

def autofill_order(apps, schema_editor):
    ShowSelectMenu = apps.get_model("api", "ShowSelectMenu")
    for menu in ShowSelectMenu.objects.all():
        i = 1
        for opt in menu.options.filter(deleted_on__isnull=True).order_by('id').all():
            opt.order = i
            i += 1
            opt.save()

class Migration(migrations.Migration):
    pass
    dependencies = [
        ('api', '0128_selectmenuoption_order'),
    ]

    operations = [
        migrations.RunPython(autofill_order)
    ]
