# Generated by Django 3.2.9 on 2022-11-09 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_autofill_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqBotCreationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('guild_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_id', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), size=None)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
