# Generated by Django 3.2.9 on 2022-11-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_faqbotcreationobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqbotcreationobject',
            old_name='channel_id',
            new_name='channel_ids',
        ),
    ]
