# Generated by Django 3.2.9 on 2022-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_faqbotcreationobject_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqbotcreationobject',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
