# Generated by Django 3.2.9 on 2022-11-16 14:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_faqbotcreationobject_admin_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), size=None)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolesets', to='api.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolesets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
