# Generated by Django 3.2.9 on 2022-11-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_userroleset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroleset',
            unique_together={('user', 'community')},
        ),
    ]
