# Generated by Django 3.2.9 on 2022-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_alter_userroleset_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='discordchannel',
            unique_together={('channel_community', 'channel_id')},
        ),
    ]
