# Generated by Django 3.2.9 on 2022-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20221121_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='faq_bot_google_spreadsheet_id',
            field=models.CharField(blank=True, help_text='Spreadsheet ID where to export FAQ bot response stats per user', max_length=100, null=True),
        ),
    ]
