# Generated by Django 3.2.9 on 2022-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20221202_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
